---
title: "Presentation Template"

output: 
  revealjs::revealjs_presentation:
    incremental: false
    transition: fade
    slide_level: 1
    css: custom.css
    reveal_options:
      controls: false
      slideNumber: 'c/t'
      progress: false
    self_contained: false
    reveal_plugins: ["notes"]
    showNotes: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Agenda

- Basics
- Formatting
- Content
- Movement
- Other

# Basics {data-background=red}
 
# How to view the presentation {data-background="background.png"}

- Click Knit to see the presentation
- After knitting, press arrow keys or space to navigate
- Press 'o' to see the overview and 'f' to go back to full screen    

---

- This slide has no title because it uses a horizontal rule

- goes vertical if slide_level: 2

# cucumber

<div class="fragment" style="margin-top: 50px; margin-bottom: 50px;">
- Only works when incremental: false (or need extra clicks)
</div>
<div class="fragment" style="margin-top: 50px; margin-bottom: 50px;">
- separate classes by a space
  <div class="fragment">
     - cake
  </div>   
  <div class="fragment">
     - cake
  </div>   
  <div class="fragment">
     - cake
  </div>   
</div>
<div class="fragment" style="margin-top: 50px; margin-bottom: 50px;">
- **eggs**
    - tomato
    - banana
</div>

<aside class="notes">
These are some notes
</aside>

# section slide

<aside class="notes">
These are some notes
</aside>

# font

- second slide

# transitions

# fragments

# speaker notes

- hit 's' on keyboard

# list style types

# images

<aside class="notes">
These are some more notes
</aside>

# two-column

# progress bar

# Gitpages

- Push to Github
- Set up pages
- Move JS up into main folder
- specify presentation in URL

# printing

- download npm
- $ npm install decktape
- $ `npm bin`/decktape
- (wherever node is)

# print 2

- `npm bin`/decktape reveal https://williamtylerbradley.github.io/presentation_templates/pres_template.html test.pdf
- `npm bin`/decktape --screenshots --screenshots-format=png --screenshots-directory=Documents reveal https://williamtylerbradley.github.io/presentation_templates/pres_template.html test.pdf


